- hosts: localhost
  become: true
  pre_tasks:
    name: Update rapositories
    apt: update_cache=yes
    changed_when: False

  tasks:
  - name: Install packages
    apt: name={{item}}
    with items:
      - htop
      - tmux
