- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
  - apt_repository:
      repo: ppa:wireshark-dev/stable
      state: present
  - apt_repository:
      repo: ppa:mystic-mirage/pycharm
      state: present
  - include: tasks/users.yml
  - include: tasks/packages.yml
  - include: tasks/cron.yml
  - include: tasks/gnome.yml
