- name: Install Wireshark
  apt:
    name: wireshark    
- name: VirtualBox
  apt:
    name: virtualbox
- name: VirtualBox Extension Package
  apt:
    name: virtualbox-ext-pack
- name: PyCharm
  apt:
    name: pycharm-community
